from pathlib import Path

from fprime_stm32.cubemx_cmake import CubeMxCMakeInfo

_HEADER_TEMPLATE = """####
# Board hardware support for this project.
#
# This is deliberately owned by the project, not by the fprime-stm32
# submodule: fprime-stm32 only expects a target named `FprimeStm32` to exist
# and only supplies hardware-agnostic OSAL delegates/drivers on top of it.
# Swapping to different hardware means editing this directory (regenerate
# %(hal_dir_name)s/ from its .ioc in CubeMX and re-running `fprime-stm32 sync`),
# never forking the submodule.
#
# Generated by `fprime-stm32 sync` from
# %(hal_dir_name)s/cmake/stm32cubemx/CMakeLists.txt (CubeMX's own generated
# source-of-truth for the enabled peripherals/HAL modules). Re-run sync after
# regenerating %(hal_dir_name)s/ from CubeMX instead of hand-editing this file.
####

if (FPRIME_PLATFORM STREQUAL "stm32h7")
    set(FPRIME_STM32_HAL_SOURCES
%(hal_sources)s
    )

    add_library(FprimeStm32 STATIC ${FPRIME_STM32_HAL_SOURCES})

    target_include_directories(FprimeStm32 PUBLIC
        "${PROJECT_SOURCE_DIR}"
        "${CMAKE_BINARY_DIR}"
        "${FPRIME_PROJECT_ROOT}"
        "${CMAKE_CURRENT_BINARY_DIR}"
%(include_dirs)s
    )

    target_compile_definitions(FprimeStm32 PUBLIC %(defines)s)

    target_compile_options(FprimeStm32 PRIVATE -ffunction-sections -fdata-sections)

    target_link_libraries(FprimeStm32 PUBLIC PlatformStm32h7)

    # %(hal_dir_name)s/%(it_source)s is intentionally NOT compiled into the
    # FprimeStm32 static library above. GNU ld only extracts an .o from a
    # static archive when something already linked has an *undefined*
    # reference into it -- but ${FPRIME_STM32_STARTUP_SOURCE} already
    # provides `.weak` Default_Handler aliases for every vector table entry
    # (and is linked directly into the executable, not via an archive), so
    # every vector is "satisfied" before the linker ever needs to search
    # this archive. That would silently discard the real ISR bodies in
    # favor of the weak infinite-loop aliases. Instead, link
    # ${FPRIME_STM32_IT_SOURCE} directly into each deployment executable's
    # own sources so its strong definitions always override the weak ones.
    set(FPRIME_STM32_LINKER_SCRIPT
        "${CMAKE_CURRENT_LIST_DIR}/linker/%(linker_out_name)s" CACHE INTERNAL "")
    set(FPRIME_STM32_STARTUP_SOURCE
        "${CMAKE_CURRENT_LIST_DIR}/startup/%(startup_out_name)s" CACHE INTERNAL "")
    set(FPRIME_STM32_IT_SOURCE
        "${CMAKE_CURRENT_LIST_DIR}/%(hal_dir_name)s/%(it_source)s" CACHE INTERNAL "")
endif()
"""


def discover_extra_config_sources(hardware_dir: Path) -> list[str]:
    config_src = hardware_dir / "config" / "src"
    if not config_src.is_dir():
        return []
    sources = sorted(config_src.glob("*.c")) + sorted(config_src.glob("*.cpp"))
    return [f"config/src/{p.name}" for p in sources]


def render_hardware_cmakelists(
    hal_dir_name: str,
    info: CubeMxCMakeInfo,
    linker_out_name: str,
    startup_out_name: str,
    extra_config_sources: list[str],
    hardware_dir: Path,
) -> str:
    hal_sources = (
        [f"{hal_dir_name}/{path}" for path in info.driver_sources]
        + [f"{hal_dir_name}/{path}" for path in info.application_sources]
        + list(extra_config_sources)
    )
    include_dirs = [f"        \"${{CMAKE_CURRENT_LIST_DIR}}/{hal_dir_name}/{path}\"" for path in info.include_dirs]
    if (hardware_dir / "config" / "include").is_dir():
        include_dirs.insert(0, '        "${CMAKE_CURRENT_LIST_DIR}/config/include"')

    return _HEADER_TEMPLATE % {
        "hal_dir_name": hal_dir_name,
        "hal_sources": "\n".join(f"        {source}" for source in hal_sources),
        "include_dirs": "\n".join(include_dirs),
        "defines": " ".join(info.all_defines),
        "it_source": info.it_source,
        "linker_out_name": linker_out_name,
        "startup_out_name": startup_out_name,
    }
