// ======================================================================
// \title  Stm32I2cDriver.cpp
// \author ivanlara
// \brief  HAL boundary for the STM32H7 I2C blocking master driver (real
//         hardware implementation, stm32h7 target only). This is the only
//         file in this driver allowed to include i2c.h/HAL_I2C_* -- see
//         Stm32I2cDriverStub.cpp for the host unit-test stand-in.
// ======================================================================

#include <fprime-stm32/Drv/STM32I2cDriver/Stm32I2cDriver.hpp>
#include <Fw/Types/Assert.hpp>

#include "i2c.h"

namespace {

// CubeMX-computed I2C1 Timing register presets for this project's actual D2PCLK1 peripheral clock.
constexpr uint32_t I2C_TIMING_STANDARD_100KHZ = 0x307075B1U;
constexpr uint32_t I2C_TIMING_FAST_400KHZ = 0x00B03FDBU;
constexpr uint32_t I2C_TIMING_FASTPLUS_1MHZ = 0x0050174FU;

//! Single-instance HAL handle pointer, set once in the real hwOpen() and
//! used by every subsequent hw* call -- mirrors Stm32UartDriver's s_huart.
I2C_HandleTypeDef* s_hi2c = nullptr;

//! Convert a HAL-free I2cInstance to the corresponding HAL handle. Only
//! I2c1 has a CubeMX-generated handle in this project today.
I2C_HandleTypeDef* toHalHandle(Stm32::I2cInstance instance) {
    //! The cases for each I2C instance. If your project uses additional instances,
    //! you need to add them here and ensure the corresponding HAL handle is returned, after
    //! you update the files from CubeMX autogenerated code into lib/fprime-stm32/src/i2c.c.
    I2C_HandleTypeDef* deviceHandle = nullptr;

    switch (instance) {
        case Stm32::I2cInstance::I2c1:
            #if I2C1_INSTANCE
            deviceHandle = &hi2c1;
            #endif
            break;
        case Stm32::I2cInstance::I2c2:
            #if I2C2_INSTANCE
            deviceHandle = &hi2c2;
            #endif
            break;
        case Stm32::I2cInstance::I2c3:
            #if I2C3_INSTANCE
            deviceHandle = &hi2c3;
            #endif
            break;
        case Stm32::I2cInstance::I2c4:
            #if I2C4_INSTANCE
            deviceHandle = &hi2c4;
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
    return deviceHandle;
}

//! Call the CubeMX-generated init function for the selected instance.
void callInstanceInit(Stm32::I2cInstance instance) {
    //! The cases for each I2C instance. If your project uses additional instances,
    //! you need to add the correspondent Initialization fuction, just after you 
    //! update the files from CubeMX autogenerated code into lib/fprime-stm32/src/i2c.c.
    switch (instance) {
        case Stm32::I2cInstance::I2c1:
            #if I2C1_INSTANCE
            MX_I2C1_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c2:
            #if I2C2_INSTANCE
            MX_I2C2_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c3:
            #if I2C3_INSTANCE
            MX_I2C3_Init();
            #endif
            break;
        case Stm32::I2cInstance::I2c4:
            #if I2C4_INSTANCE
            MX_I2C4_Init();
            #endif
            break;
        default:
            FW_ASSERT(false, static_cast<FwAssertArgType>(instance));
            break;
    }
}

//! Map a requested bus speed preset to its CubeMX-computed Timing value.
uint32_t toTiming(Stm32::I2cBusSpeed busSpeed) {
    switch (busSpeed) {
        case Stm32::I2cBusSpeed::Standard:
            return I2C_TIMING_STANDARD_100KHZ;
        case Stm32::I2cBusSpeed::Fast:
            return I2C_TIMING_FAST_400KHZ;
        case Stm32::I2cBusSpeed::FastPlus:
            return I2C_TIMING_FASTPLUS_1MHZ;
        default:
            return I2C_TIMING_FAST_400KHZ;
    }
}

}  // namespace

namespace Stm32 {

Fw::Success Stm32I2cDriver ::open(I2cInstance instance, I2cBusSpeed busSpeed) {
    I2C_HandleTypeDef* const halHandle = toHalHandle(instance);
    FW_ASSERT(halHandle != nullptr, static_cast<FwAssertArgType>(instance));

    // MX_I2Cn_Init() traps in Error_Handler() on failure rather than
    // returning a status (matches every other CubeMX-generated
    // MX_*_Init() in this project).
    callInstanceInit(instance);

    const uint32_t timing = toTiming(busSpeed);
    if (timing != halHandle->Init.Timing) {
        halHandle->Init.Timing = timing;
        if (HAL_I2C_Init(halHandle) != HAL_OK) {
            return Fw::Success::FAILURE;
        }
    }

    s_hi2c = halHandle;
    this->m_opened = true;

    Fw::LogStringArg _speedArg(busSpeed == Stm32::I2cBusSpeed::Standard ? "Standard" :
                               busSpeed == Stm32::I2cBusSpeed::Fast ? "Fast" :
                               busSpeed == Stm32::I2cBusSpeed::FastPlus ? "FastPlus" : "Unknown");
    
    this->log_ACTIVITY_HI_PortOpened(_speedArg);
    return Fw::Success::SUCCESS;
}

//! Address-phase NACK (no device answered) is reported via HAL_I2C_GetError(),
//! not the HAL_StatusTypeDef -- distinguishes I2C_ADDRESS_ERR from a
//! data-phase/bus I2C_WRITE_ERR/I2C_READ_ERR.
Drv::I2cStatus Stm32I2cDriver ::hwMasterTransmit(U16 devAddress, U8* data, U16 len) {
    
    FW_ASSERT(data!=nullptr);
    
    const HAL_StatusTypeDef status =
        HAL_I2C_Master_Transmit(s_hi2c, static_cast<uint16_t>(devAddress << 1U), data, len, TRANSACTION_TIMEOUT_MS);
    if (status == HAL_OK) {
        return Drv::I2cStatus::I2C_OK;
    }
    Fw::LogStringArg _op("Master_Transmit");
    this->log_WARNING_HI_HalError(_op, devAddress, static_cast<I32>(status));
    return ((HAL_I2C_GetError(s_hi2c) & HAL_I2C_ERROR_AF) != 0U) ? Drv::I2cStatus::I2C_ADDRESS_ERR
                                                                  : Drv::I2cStatus::I2C_WRITE_ERR;
}

Drv::I2cStatus Stm32I2cDriver ::hwMasterReceive(U16 devAddress, U8* data, U16 len) {
    
    FW_ASSERT(data!=nullptr);
    
    const HAL_StatusTypeDef status =
        HAL_I2C_Master_Receive(s_hi2c, static_cast<uint16_t>(devAddress << 1U), data, len, TRANSACTION_TIMEOUT_MS);
    if (status == HAL_OK) {
        return Drv::I2cStatus::I2C_OK;
    }
    Fw::LogStringArg _op("Master_Receive");
    this->log_WARNING_HI_HalError(_op, devAddress, static_cast<I32>(status));
    return ((HAL_I2C_GetError(s_hi2c) & HAL_I2C_ERROR_AF) != 0U) ? Drv::I2cStatus::I2C_ADDRESS_ERR
                                                                  : Drv::I2cStatus::I2C_READ_ERR;
}

}  // namespace Stm32